default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: user
  password: password

development:
  <<: *default
  database: leoproject_development

test:
  <<: *default
  database: leoproject_test

production:
  <<: *default
  database: leoproject_production